/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { Uint128, Logo, Binary, Expiration } from "./Cw20.types";
export interface Cw20Msg {
    contractAddress: string;
    sender: string;
    transfer: ({ amount, recipient }: {
        amount: Uint128;
        recipient: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    burn: ({ amount }: {
        amount: Uint128;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    send: ({ amount, contract, msg }: {
        amount: Uint128;
        contract: string;
        msg: Binary;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    increaseAllowance: ({ amount, expires, spender }: {
        amount: Uint128;
        expires?: Expiration;
        spender: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    decreaseAllowance: ({ amount, expires, spender }: {
        amount: Uint128;
        expires?: Expiration;
        spender: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    transferFrom: ({ amount, owner, recipient }: {
        amount: Uint128;
        owner: string;
        recipient: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    sendFrom: ({ amount, contract, msg, owner }: {
        amount: Uint128;
        contract: string;
        msg: Binary;
        owner: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    burnFrom: ({ amount, owner }: {
        amount: Uint128;
        owner: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    mint: ({ amount, recipient }: {
        amount: Uint128;
        recipient: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateMinter: ({ newMinter }: {
        newMinter?: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateMarketing: ({ description, marketing, project }: {
        description?: string;
        marketing?: string;
        project?: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    uploadLogo: (logo: Logo, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class Cw20MsgComposer implements Cw20Msg {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    transfer: ({ amount, recipient }: {
        amount: Uint128;
        recipient: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    burn: ({ amount }: {
        amount: Uint128;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    send: ({ amount, contract, msg }: {
        amount: Uint128;
        contract: string;
        msg: Binary;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    increaseAllowance: ({ amount, expires, spender }: {
        amount: Uint128;
        expires?: Expiration | undefined;
        spender: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    decreaseAllowance: ({ amount, expires, spender }: {
        amount: Uint128;
        expires?: Expiration | undefined;
        spender: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    transferFrom: ({ amount, owner, recipient }: {
        amount: Uint128;
        owner: string;
        recipient: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    sendFrom: ({ amount, contract, msg, owner }: {
        amount: Uint128;
        contract: string;
        msg: Binary;
        owner: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    burnFrom: ({ amount, owner }: {
        amount: Uint128;
        owner: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    mint: ({ amount, recipient }: {
        amount: Uint128;
        recipient: string;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateMinter: ({ newMinter }: {
        newMinter?: string | undefined;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateMarketing: ({ description, marketing, project }: {
        description?: string | undefined;
        marketing?: string | undefined;
        project?: string | undefined;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    uploadLogo: (logo: Logo, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
