/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, Action, QueryMsg } from "./FuzioIDOInfo.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class FuzioIDOInfoExecuteMsgBuilder {
    static updateConfig: ({ newConfig }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_config: unknown;
    }>["update_config"]>) => ExecuteMsg;
    static updateOwnership: (action: Action) => ExecuteMsg;
}
export declare abstract class FuzioIDOInfoQueryMsgBuilder {
    static config: () => QueryMsg;
}
