/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, Action, Config, QueryMsg } from "./FuzioIDOInfo.types";
export declare abstract class FuzioIDOInfoExecuteMsgBuilder {
    static updateConfig: ({ newConfig }: CamelCasedProperties<{
        new_config: Config;
    }>) => ExecuteMsg;
    static updateOwnership: (action: Action) => ExecuteMsg;
}
export declare abstract class FuzioIDOInfoQueryMsgBuilder {
    static config: () => QueryMsg;
}
