/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { WalletInfo, ExecuteMsg, Expiration, TokenSelect, QueryMsg } from "./FuzioPool.types";
export declare abstract class FuzioPoolExecuteMsgBuilder {
    static addLiquidity: ({ expiration, maxToken2, minLiquidity, token1Amount }: CamelCasedProperties<{
        expiration?: Expiration | null | undefined;
        max_token2: string;
        min_liquidity: string;
        token1_amount: string;
    }>) => ExecuteMsg;
    static removeLiquidity: ({ amount, expiration, minToken1, minToken2 }: CamelCasedProperties<{
        amount: string;
        expiration?: Expiration | null | undefined;
        min_token1: string;
        min_token2: string;
    }>) => ExecuteMsg;
    static swap: ({ expiration, inputAmount, inputToken, minOutput }: CamelCasedProperties<{
        expiration?: Expiration | null | undefined;
        input_amount: string;
        input_token: TokenSelect;
        min_output: string;
    }>) => ExecuteMsg;
    static passThroughSwap: ({ expiration, inputToken, inputTokenAmount, outputAmmAddress, outputMinToken }: CamelCasedProperties<{
        expiration?: Expiration | null | undefined;
        input_token: TokenSelect;
        input_token_amount: string;
        output_amm_address: string;
        output_min_token: string;
    }>) => ExecuteMsg;
    static swapAndSendTo: ({ expiration, inputAmount, inputToken, minToken, recipient }: CamelCasedProperties<{
        expiration?: Expiration | null | undefined;
        input_amount: string;
        input_token: TokenSelect;
        min_token: string;
        recipient: string;
    }>) => ExecuteMsg;
    static updateConfig: ({ devWalletLists, feePercentDenominator, feePercentNumerator, owner }: CamelCasedProperties<{
        dev_wallet_lists: WalletInfo[];
        fee_percent_denominator: string;
        fee_percent_numerator: string;
        owner?: string | null | undefined;
    }>) => ExecuteMsg;
}
export declare abstract class FuzioPoolQueryMsgBuilder {
    static info: () => QueryMsg;
    static token1ForToken2Price: ({ token1Amount }: CamelCasedProperties<{
        token1_amount: string;
    }>) => QueryMsg;
    static token2ForToken1Price: ({ token2Amount }: CamelCasedProperties<{
        token2_amount: string;
    }>) => QueryMsg;
    static fee: () => QueryMsg;
}
