/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, QueryMsg } from "./FuzioNativePrediction.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class FuzioNativePredictionExecuteMsgBuilder {
    static updateConfig: ({ config }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_config: unknown;
    }>["update_config"]>) => ExecuteMsg;
    static betBull: ({ amount, roundId }: CamelCasedProperties<Extract<ExecuteMsg, {
        bet_bull: unknown;
    }>["bet_bull"]>) => ExecuteMsg;
    static betBear: ({ amount, roundId }: CamelCasedProperties<Extract<ExecuteMsg, {
        bet_bear: unknown;
    }>["bet_bear"]>) => ExecuteMsg;
    static closeRound: () => ExecuteMsg;
    static collectWinnings: () => ExecuteMsg;
    static collectionWinningRound: ({ roundId }: CamelCasedProperties<Extract<ExecuteMsg, {
        collection_winning_round: unknown;
    }>["collection_winning_round"]>) => ExecuteMsg;
    static halt: () => ExecuteMsg;
    static resume: () => ExecuteMsg;
    static addAdmin: ({ newAdmin }: CamelCasedProperties<Extract<ExecuteMsg, {
        add_admin: unknown;
    }>["add_admin"]>) => ExecuteMsg;
    static removeAdmin: ({ oldAdmin }: CamelCasedProperties<Extract<ExecuteMsg, {
        remove_admin: unknown;
    }>["remove_admin"]>) => ExecuteMsg;
    static modifyDevWallet: ({ newDevWallets }: CamelCasedProperties<Extract<ExecuteMsg, {
        modify_dev_wallet: unknown;
    }>["modify_dev_wallet"]>) => ExecuteMsg;
}
export declare abstract class FuzioNativePredictionQueryMsgBuilder {
    static config: () => QueryMsg;
    static status: () => QueryMsg;
    static myCurrentPosition: ({ address }: CamelCasedProperties<Extract<QueryMsg, {
        my_current_position: unknown;
    }>["my_current_position"]>) => QueryMsg;
    static finishedRound: ({ roundId }: CamelCasedProperties<Extract<QueryMsg, {
        finished_round: unknown;
    }>["finished_round"]>) => QueryMsg;
    static myGameList: ({ limit, player, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        my_game_list: unknown;
    }>["my_game_list"]>) => QueryMsg;
    static myPendingReward: ({ player }: CamelCasedProperties<Extract<QueryMsg, {
        my_pending_reward: unknown;
    }>["my_pending_reward"]>) => QueryMsg;
    static myPendingRewardRounds: ({ player }: CamelCasedProperties<Extract<QueryMsg, {
        my_pending_reward_rounds: unknown;
    }>["my_pending_reward_rounds"]>) => QueryMsg;
    static getUsersPerRound: ({ limit, roundId, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        get_users_per_round: unknown;
    }>["get_users_per_round"]>) => QueryMsg;
    static myPendingRewardRound: ({ player, roundId }: CamelCasedProperties<Extract<QueryMsg, {
        my_pending_reward_round: unknown;
    }>["my_pending_reward_round"]>) => QueryMsg;
    static getClaimInfoPerRound: ({ limit, roundId, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        get_claim_info_per_round: unknown;
    }>["get_claim_info_per_round"]>) => QueryMsg;
    static getClaimInfoByUser: ({ limit, player, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        get_claim_info_by_user: unknown;
    }>["get_claim_info_by_user"]>) => QueryMsg;
    static totalSpent: ({ player }: CamelCasedProperties<Extract<QueryMsg, {
        total_spent: unknown;
    }>["total_spent"]>) => QueryMsg;
    static getAdmins: () => QueryMsg;
}
