/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, QueryMsg } from "./FuzioNativeIDO.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class FuzioNativeIDOExecuteMsgBuilder {
    static buyToken: () => ExecuteMsg;
    static claimToken: () => ExecuteMsg;
    static changeAdmin: ({ address }: CamelCasedProperties<Extract<ExecuteMsg, {
        change_admin: unknown;
    }>["change_admin"]>) => ExecuteMsg;
    static withdrawTokenNotSoldByAdmin: () => ExecuteMsg;
}
export declare abstract class FuzioNativeIDOQueryMsgBuilder {
    static getStateInfo: () => QueryMsg;
    static getUserInfo: ({ address }: CamelCasedProperties<Extract<QueryMsg, {
        get_user_info: unknown;
    }>["get_user_info"]>) => QueryMsg;
    static getSaleInfo: () => QueryMsg;
    static getClaimableAmount: ({ address }: CamelCasedProperties<Extract<QueryMsg, {
        get_claimable_amount: unknown;
    }>["get_claimable_amount"]>) => QueryMsg;
    static getClaimableTime: ({ address }: CamelCasedProperties<Extract<QueryMsg, {
        get_claimable_time: unknown;
    }>["get_claimable_time"]>) => QueryMsg;
    static getUserInfos: ({ limit, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        get_user_infos: unknown;
    }>["get_user_infos"]>) => QueryMsg;
}
