/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, QueryMsg } from "./FuzioStaking.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class FuzioStakingExecuteMsgBuilder {
    static receive: ({ amount, msg, sender }: CamelCasedProperties<Extract<ExecuteMsg, {
        receive: unknown;
    }>["receive"]>) => ExecuteMsg;
    static unbond: ({ amount }: CamelCasedProperties<Extract<ExecuteMsg, {
        unbond: unknown;
    }>["unbond"]>) => ExecuteMsg;
    static withdraw: () => ExecuteMsg;
    static redeem: () => ExecuteMsg;
    static updateAdmin: ({ admin }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_admin: unknown;
    }>["update_admin"]>) => ExecuteMsg;
    static updateConfig: ({ distributionSchedule }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_config: unknown;
    }>["update_config"]>) => ExecuteMsg;
    static updateTokenContract: ({ lpTokenContract, rewardToken }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_token_contract: unknown;
    }>["update_token_contract"]>) => ExecuteMsg;
    static updateTokensAndDistribution: ({ distributionSchedule, lpTokenContract, rewardToken }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_tokens_and_distribution: unknown;
    }>["update_tokens_and_distribution"]>) => ExecuteMsg;
    static updateLockDuration: ({ lockDuration }: CamelCasedProperties<Extract<ExecuteMsg, {
        update_lock_duration: unknown;
    }>["update_lock_duration"]>) => ExecuteMsg;
}
export declare abstract class FuzioStakingQueryMsgBuilder {
    static config: () => QueryMsg;
    static state: ({ blockTime }: CamelCasedProperties<Extract<QueryMsg, {
        state: unknown;
    }>["state"]>) => QueryMsg;
    static stakerInfo: ({ staker }: CamelCasedProperties<Extract<QueryMsg, {
        staker_info: unknown;
    }>["staker_info"]>) => QueryMsg;
    static allStakers: ({ limit, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        all_stakers: unknown;
    }>["all_stakers"]>) => QueryMsg;
    static unbondingInfo: ({ limit, staker, startAfter }: CamelCasedProperties<Extract<QueryMsg, {
        unbonding_info: unknown;
    }>["unbonding_info"]>) => QueryMsg;
}
