/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.28.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { Action, Config } from "./FuzioIDOInfo.types";
export interface FuzioIDOInfoMessage {
    contractAddress: string;
    sender: string;
    updateConfig: ({ newConfig }: {
        newConfig: Config;
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateOwnership: (action: Action, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class FuzioIDOInfoMessageComposer implements FuzioIDOInfoMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    updateConfig: ({ newConfig }: {
        newConfig: Config;
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateOwnership: (action: Action, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
