/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { ExecuteMsg, QueryMsg } from "./FuzioPoolList.types";
import { CamelCasedProperties } from "type-fest";
export declare abstract class FuzioPoolListExecuteMsgBuilder {
    static createPool: ({ burnRatio, swapFee, token1, token2 }: CamelCasedProperties<Extract<ExecuteMsg, {
        create_pool: unknown;
    }>["create_pool"]>) => ExecuteMsg;
    static listToken: ({ chain, decimal, denom, fullName, isIbcCoin, isNativeCoin, logoUri, symbol }: CamelCasedProperties<Extract<ExecuteMsg, {
        list_token: unknown;
    }>["list_token"]>) => ExecuteMsg;
    static changeConfig: ({ burnFeePercent, devWalletLists, poolCreationFee, tokenListingFee }: CamelCasedProperties<Extract<ExecuteMsg, {
        change_config: unknown;
    }>["change_config"]>) => ExecuteMsg;
}
export declare abstract class FuzioPoolListQueryMsgBuilder {
    static tokens: () => QueryMsg;
    static pools: () => QueryMsg;
    static config: () => QueryMsg;
}
