/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { Action, Config } from "./FuzioIDOInfo.types";
export interface FuzioIDOInfoMsg {
    contractAddress: string;
    sender: string;
    updateConfig: ({ newConfig }: {
        newConfig: Config;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateOwnership: (action: Action, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class FuzioIDOInfoMsgComposer implements FuzioIDOInfoMsg {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    updateConfig: ({ newConfig }: {
        newConfig: Config;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    updateOwnership: (action: Action, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
