/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export type Decimal = string;
export type Addr = string;
export type Uint128 = string;
export interface InstantiateMsg {
    burn_fee_percent: number;
    dev_wallet_list: WalletInfo[];
    initial_pools?: Pool[] | null;
    initial_tokens?: Token[] | null;
    pool_creation_fee: Coin;
    token_listing_fee: Coin;
}
export interface WalletInfo {
    address: string;
    ratio: Decimal;
}
export interface Pool {
    burn_ratio: number;
    creator: Addr;
    swap_fee: string;
    token1: string;
    token2: string;
}
export interface Token {
    chain: Chain;
    decimal: number;
    denom: string;
    full_name: string;
    is_ibc_coin: boolean;
    is_native_coin: boolean;
    logo_uri: string;
    symbol: string;
}
export interface Chain {
    chain_id: string;
    chain_name: string;
    gas_price: GasPrice;
    ibc_channels?: IbcChannels | null;
    is_evm: boolean;
}
export interface GasPrice {
    amount: number;
    denom: string;
}
export interface IbcChannels {
    deposit_channel: string;
    withdraw_channel: string;
}
export interface Coin {
    amount: Uint128;
    denom: string;
    [k: string]: unknown;
}
export type ExecuteMsg = {
    create_pool: {
        burn_ratio: number;
        swap_fee: string;
        token1: string;
        token2: string;
    };
} | {
    list_token: {
        chain: Chain;
        decimal: number;
        denom: string;
        full_name: string;
        is_ibc_coin: boolean;
        is_native_coin: boolean;
        logo_uri: string;
        symbol: string;
    };
} | {
    change_config: {
        burn_fee_percent: number;
        dev_wallet_lists: WalletInfo[];
        pool_creation_fee: Coin;
        token_listing_fee: Coin;
    };
};
export type QueryMsg = {
    tokens: {};
} | {
    pools: {};
} | {
    config: {};
};
export interface ConfigResp {
    config: Config;
}
export interface Config {
    burn_fee_percent: number;
    dev_wallet_list: WalletInfo[];
    pool_creation_fee: Coin;
    token_listing_fee: Coin;
}
export interface PoolsResp {
    pools: Pool[];
}
export interface TokensResp {
    tokens: Token[];
}
export type FuzioPoolListExecuteMsg = ExecuteMsg;
