/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { WalletInfo, Chain, Coin, ExecuteMsg, QueryMsg } from "./FuzioPoolList.types";
export declare abstract class FuzioPoolListExecuteMsgBuilder {
    static createPool: ({ burnRatio, swapFee, token1, token2 }: CamelCasedProperties<{
        burn_ratio: number;
        swap_fee: string;
        token1: string;
        token2: string;
    }>) => ExecuteMsg;
    static listToken: ({ chain, decimal, denom, fullName, isIbcCoin, isNativeCoin, logoUri, symbol }: CamelCasedProperties<{
        chain: Chain;
        decimal: number;
        denom: string;
        full_name: string;
        is_ibc_coin: boolean;
        is_native_coin: boolean;
        logo_uri: string;
        symbol: string;
    }>) => ExecuteMsg;
    static changeConfig: ({ burnFeePercent, devWalletLists, poolCreationFee, tokenListingFee }: CamelCasedProperties<{
        burn_fee_percent: number;
        dev_wallet_lists: WalletInfo[];
        pool_creation_fee: Coin;
        token_listing_fee: Coin;
    }>) => ExecuteMsg;
}
export declare abstract class FuzioPoolListQueryMsgBuilder {
    static tokens: () => QueryMsg;
    static pools: () => QueryMsg;
    static config: () => QueryMsg;
}
