/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { Addr, Uint128, Config, WalletInfo } from "./FuzioNativePrediction.types";
export interface FuzioNativePredictionMsg {
    contractAddress: string;
    sender: string;
    updateConfig: ({ config }: {
        config: Config;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    betBull: ({ amount, roundId }: {
        amount: Uint128;
        roundId: Uint128;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    betBear: ({ amount, roundId }: {
        amount: Uint128;
        roundId: Uint128;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    closeRound: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    collectWinnings: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    collectionWinningRound: ({ roundId }: {
        roundId: Uint128;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    halt: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    resume: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    addAdmin: ({ newAdmin }: {
        newAdmin: Addr;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    removeAdmin: ({ oldAdmin }: {
        oldAdmin: Addr;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    modifyDevWallet: ({ newDevWallets }: {
        newDevWallets: WalletInfo[];
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class FuzioNativePredictionMsgComposer implements FuzioNativePredictionMsg {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    updateConfig: ({ config }: {
        config: Config;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    betBull: ({ amount, roundId }: {
        amount: Uint128;
        roundId: Uint128;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    betBear: ({ amount, roundId }: {
        amount: Uint128;
        roundId: Uint128;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    closeRound: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    collectWinnings: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    collectionWinningRound: ({ roundId }: {
        roundId: Uint128;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    halt: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    resume: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
    addAdmin: ({ newAdmin }: {
        newAdmin: Addr;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    removeAdmin: ({ oldAdmin }: {
        oldAdmin: Addr;
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
    modifyDevWallet: ({ newDevWallets }: {
        newDevWallets: WalletInfo[];
    }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
