/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./FuzioNativePrediction.client";
import * as _2 from "./FuzioNativePrediction.message-composer";
import * as _3 from "./FuzioNativePrediction.message-builder";
import * as _5 from "./FuzioNativeIDO.client";
import * as _6 from "./FuzioNativeIDO.message-composer";
import * as _7 from "./FuzioNativeIDO.message-builder";
import * as _9 from "./FuzioIDOInfo.client";
import * as _10 from "./FuzioIDOInfo.message-composer";
import * as _11 from "./FuzioIDOInfo.message-builder";
import * as _13 from "./FuzioPool.client";
import * as _14 from "./FuzioPool.message-composer";
import * as _15 from "./FuzioPool.message-builder";
import * as _17 from "./FuzioPoolList.client";
import * as _18 from "./FuzioPoolList.message-composer";
import * as _19 from "./FuzioPoolList.message-builder";
import * as _21 from "./FuzioStaking.client";
import * as _22 from "./FuzioStaking.message-composer";
import * as _23 from "./FuzioStaking.message-builder";
import * as _25 from "./Cw20.client";
import * as _26 from "./Cw20.message-composer";
import * as _27 from "./Cw20.message-builder";
export declare namespace contracts {
    const FuzioNativePrediction: {
        FuzioNativePredictionExecuteMsgBuilder: typeof _3.FuzioNativePredictionExecuteMsgBuilder;
        FuzioNativePredictionQueryMsgBuilder: typeof _3.FuzioNativePredictionQueryMsgBuilder;
        FuzioNativePredictionMsgComposer: typeof _2.FuzioNativePredictionMsgComposer;
        FuzioNativePredictionQueryClient: typeof _1.FuzioNativePredictionQueryClient;
        FuzioNativePredictionClient: typeof _1.FuzioNativePredictionClient;
    };
    const FuzioNativeIDO: {
        FuzioNativeIDOExecuteMsgBuilder: typeof _7.FuzioNativeIDOExecuteMsgBuilder;
        FuzioNativeIDOQueryMsgBuilder: typeof _7.FuzioNativeIDOQueryMsgBuilder;
        FuzioNativeIDOMsgComposer: typeof _6.FuzioNativeIDOMsgComposer;
        FuzioNativeIDOQueryClient: typeof _5.FuzioNativeIDOQueryClient;
        FuzioNativeIDOClient: typeof _5.FuzioNativeIDOClient;
    };
    const FuzioIDOInfo: {
        FuzioIDOInfoExecuteMsgBuilder: typeof _11.FuzioIDOInfoExecuteMsgBuilder;
        FuzioIDOInfoQueryMsgBuilder: typeof _11.FuzioIDOInfoQueryMsgBuilder;
        FuzioIDOInfoMsgComposer: typeof _10.FuzioIDOInfoMsgComposer;
        FuzioIDOInfoQueryClient: typeof _9.FuzioIDOInfoQueryClient;
        FuzioIDOInfoClient: typeof _9.FuzioIDOInfoClient;
    };
    const FuzioPool: {
        FuzioPoolExecuteMsgBuilder: typeof _15.FuzioPoolExecuteMsgBuilder;
        FuzioPoolQueryMsgBuilder: typeof _15.FuzioPoolQueryMsgBuilder;
        FuzioPoolMsgComposer: typeof _14.FuzioPoolMsgComposer;
        FuzioPoolQueryClient: typeof _13.FuzioPoolQueryClient;
        FuzioPoolClient: typeof _13.FuzioPoolClient;
    };
    const FuzioPoolList: {
        FuzioPoolListExecuteMsgBuilder: typeof _19.FuzioPoolListExecuteMsgBuilder;
        FuzioPoolListQueryMsgBuilder: typeof _19.FuzioPoolListQueryMsgBuilder;
        FuzioPoolListMsgComposer: typeof _18.FuzioPoolListMsgComposer;
        FuzioPoolListQueryClient: typeof _17.FuzioPoolListQueryClient;
        FuzioPoolListClient: typeof _17.FuzioPoolListClient;
    };
    const FuzioStaking: {
        FuzioStakingExecuteMsgBuilder: typeof _23.FuzioStakingExecuteMsgBuilder;
        FuzioStakingQueryMsgBuilder: typeof _23.FuzioStakingQueryMsgBuilder;
        FuzioStakingMsgComposer: typeof _22.FuzioStakingMsgComposer;
        FuzioStakingQueryClient: typeof _21.FuzioStakingQueryClient;
        FuzioStakingClient: typeof _21.FuzioStakingClient;
    };
    const Cw20: {
        Cw20ExecuteMsgBuilder: typeof _27.Cw20ExecuteMsgBuilder;
        Cw20QueryMsgBuilder: typeof _27.Cw20QueryMsgBuilder;
        Cw20MsgComposer: typeof _26.Cw20MsgComposer;
        Cw20QueryClient: typeof _25.Cw20QueryClient;
        Cw20Client: typeof _25.Cw20Client;
    };
}
