/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./FuzioNativePrediction.client";
import * as _2 from "./FuzioNativePrediction.message-composer";
import * as _3 from "./FuzioNativePrediction.msg-builder";
import * as _5 from "./FuzioNativeIDO.client";
import * as _6 from "./FuzioNativeIDO.message-composer";
import * as _7 from "./FuzioNativeIDO.msg-builder";
import * as _9 from "./FuzioIDOInfo.client";
import * as _10 from "./FuzioIDOInfo.message-composer";
import * as _11 from "./FuzioIDOInfo.msg-builder";
import * as _13 from "./FuzioPool.client";
import * as _14 from "./FuzioPool.message-composer";
import * as _15 from "./FuzioPool.msg-builder";
import * as _17 from "./FuzioPoolList.client";
import * as _18 from "./FuzioPoolList.message-composer";
import * as _19 from "./FuzioPoolList.msg-builder";
import * as _21 from "./FuzioStaking.client";
import * as _22 from "./FuzioStaking.message-composer";
import * as _23 from "./FuzioStaking.msg-builder";
export declare namespace contracts {
    const FuzioNativePrediction: {
        FuzioNativePredictionExecuteMsgBuilder: typeof _3.FuzioNativePredictionExecuteMsgBuilder;
        FuzioNativePredictionQueryMsgBuilder: typeof _3.FuzioNativePredictionQueryMsgBuilder;
        FuzioNativePredictionMessageComposer: typeof _2.FuzioNativePredictionMessageComposer;
        FuzioNativePredictionQueryClient: typeof _1.FuzioNativePredictionQueryClient;
        FuzioNativePredictionClient: typeof _1.FuzioNativePredictionClient;
    };
    const FuzioNativeIDO: {
        FuzioNativeIDOExecuteMsgBuilder: typeof _7.FuzioNativeIDOExecuteMsgBuilder;
        FuzioNativeIDOQueryMsgBuilder: typeof _7.FuzioNativeIDOQueryMsgBuilder;
        FuzioNativeIDOMessageComposer: typeof _6.FuzioNativeIDOMessageComposer;
        FuzioNativeIDOQueryClient: typeof _5.FuzioNativeIDOQueryClient;
        FuzioNativeIDOClient: typeof _5.FuzioNativeIDOClient;
    };
    const FuzioIDOInfo: {
        FuzioIDOInfoExecuteMsgBuilder: typeof _11.FuzioIDOInfoExecuteMsgBuilder;
        FuzioIDOInfoQueryMsgBuilder: typeof _11.FuzioIDOInfoQueryMsgBuilder;
        FuzioIDOInfoMessageComposer: typeof _10.FuzioIDOInfoMessageComposer;
        FuzioIDOInfoQueryClient: typeof _9.FuzioIDOInfoQueryClient;
        FuzioIDOInfoClient: typeof _9.FuzioIDOInfoClient;
    };
    const FuzioPool: {
        FuzioPoolExecuteMsgBuilder: typeof _15.FuzioPoolExecuteMsgBuilder;
        FuzioPoolQueryMsgBuilder: typeof _15.FuzioPoolQueryMsgBuilder;
        FuzioPoolMessageComposer: typeof _14.FuzioPoolMessageComposer;
        FuzioPoolQueryClient: typeof _13.FuzioPoolQueryClient;
        FuzioPoolClient: typeof _13.FuzioPoolClient;
    };
    const FuzioPoolList: {
        FuzioPoolListExecuteMsgBuilder: typeof _19.FuzioPoolListExecuteMsgBuilder;
        FuzioPoolListQueryMsgBuilder: typeof _19.FuzioPoolListQueryMsgBuilder;
        FuzioPoolListMessageComposer: typeof _18.FuzioPoolListMessageComposer;
        FuzioPoolListQueryClient: typeof _17.FuzioPoolListQueryClient;
        FuzioPoolListClient: typeof _17.FuzioPoolListClient;
    };
    const FuzioStaking: {
        FuzioStakingExecuteMsgBuilder: typeof _23.FuzioStakingExecuteMsgBuilder;
        FuzioStakingQueryMsgBuilder: typeof _23.FuzioStakingQueryMsgBuilder;
        FuzioStakingMessageComposer: typeof _22.FuzioStakingMessageComposer;
        FuzioStakingQueryClient: typeof _21.FuzioStakingQueryClient;
        FuzioStakingClient: typeof _21.FuzioStakingClient;
    };
}
