/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.28.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./FuzioNativePrediction.client";
import * as _2 from "./FuzioNativePrediction.message-composer";
export declare namespace contracts {
    const FuzioNativePrediction: {
        FuzioNativePredictionMessageComposer: typeof _2.FuzioNativePredictionMessageComposer;
        FuzioNativePredictionQueryClient: typeof _1.FuzioNativePredictionQueryClient;
        FuzioNativePredictionClient: typeof _1.FuzioNativePredictionClient;
    };
}
