/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Addr, Decimal, Uint128, InstantiateMsg, WalletInfo, ExecuteMsg, Action, Expiration, Timestamp, Uint64, Config, QueryMsg } from "./FuzioIDOInfo.types";
import { CamelCasedProperties } from "type-fest";
export abstract class FuzioIDOInfoExecuteMsgBuilder {
  static updateConfig = ({
    newConfig
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_config: unknown;
  }>["update_config"]>): ExecuteMsg => {
    return {
      update_config: ({
        new_config: newConfig
      } as const)
    };
  };
  static updateOwnership = (action: Action): ExecuteMsg => {
    return {
      update_ownership: action
    };
  };
}
export abstract class FuzioIDOInfoQueryMsgBuilder {
  static config = (): QueryMsg => {
    return {
      config: ({} as const)
    };
  };
}