/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { Uint128, InstantiateMsg, IdoInfo, Description, Product, Socials, Team, TeamMember, Coin, ExecuteMsg, QueryMsg, TimeInfo, SaleInfo, Addr, Decimal, State, WalletInfo, UserInfoResponse, UserInfo, UserInfosResponse } from "./FuzioNativeIDO.types";
export interface FuzioNativeIDOMsg {
  contractAddress: string;
  sender: string;
  buyToken: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  claimToken: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  changeAdmin: ({
    address
  }: {
    address: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  withdrawTokenNotSoldByAdmin: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class FuzioNativeIDOMsgComposer implements FuzioNativeIDOMsg {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.buyToken = this.buyToken.bind(this);
    this.claimToken = this.claimToken.bind(this);
    this.changeAdmin = this.changeAdmin.bind(this);
    this.withdrawTokenNotSoldByAdmin = this.withdrawTokenNotSoldByAdmin.bind(this);
  }

  buyToken = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          buy_token: {}
        })),
        funds: _funds
      })
    };
  };
  claimToken = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          claim_token: {}
        })),
        funds: _funds
      })
    };
  };
  changeAdmin = ({
    address
  }: {
    address: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          change_admin: {
            address
          }
        })),
        funds: _funds
      })
    };
  };
  withdrawTokenNotSoldByAdmin = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          withdraw_token_not_sold_by_admin: {}
        })),
        funds: _funds
      })
    };
  };
}