/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.28.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./FuzioNativePrediction.types";
import * as _1 from "./FuzioNativePrediction.client";
import * as _2 from "./FuzioNativePrediction.message-composer";
import * as _3 from "./FuzioNativeIDO.types";
import * as _4 from "./FuzioNativeIDO.client";
import * as _5 from "./FuzioNativeIDO.message-composer";
import * as _6 from "./FuzioIDOInfo.types";
import * as _7 from "./FuzioIDOInfo.client";
import * as _8 from "./FuzioIDOInfo.message-composer";
import * as _9 from "./FuzioPool.types";
import * as _10 from "./FuzioPool.client";
import * as _11 from "./FuzioPool.message-composer";
import * as _12 from "./FuzioPoolList.types";
import * as _13 from "./FuzioPoolList.client";
import * as _14 from "./FuzioPoolList.message-composer";
import * as _15 from "./FuzioStaking.types";
import * as _16 from "./FuzioStaking.client";
import * as _17 from "./FuzioStaking.message-composer";
export namespace contracts {
  export const FuzioNativePrediction = { ..._0,
    ..._1,
    ..._2
  };
  export const FuzioNativeIDO = { ..._3,
    ..._4,
    ..._5
  };
  export const FuzioIDOInfo = { ..._6,
    ..._7,
    ..._8
  };
  export const FuzioPool = { ..._9,
    ..._10,
    ..._11
  };
  export const FuzioPoolList = { ..._12,
    ..._13,
    ..._14
  };
  export const FuzioStaking = { ..._15,
    ..._16,
    ..._17
  };
}